In [60]:
import pandas as pd
import numpy as np
import yfinance as yf
import seaborn as sns
from yahoofinancials import YahooFinancials
from matplotlib import pyplot as plt

In [61]:
symbol_list = ['HAL',
 'TIINDIA',
 'CGPOWER',
 'TRENT',
 'PRESTIGE',
 'NHPC',
 'OIL',
 'BAJAJ-AUTO',
 'SUPREMEIND',
 'SJVN']

In [62]:
start_date = "2021-04-01"
end_date = "2024-05-01"

In [63]:
data =[]
asset = []

In [64]:
for i in symbol_list:
    stock = pd.read_csv(f'{i}.csv', usecols=['Date','Close','Adj Close','Volume'])
    stock.set_index('Date', inplace=True)
    # Rename columns to include the stock symbol
    stock.columns = pd.MultiIndex.from_product([[i], stock.columns])
    #stock['Symbol'] = i
    data.append(stock)

In [65]:
type(data)

list

In [66]:
combined_df = pd.concat(data,axis=1)
# Reset index to ensure the 'Date' column is not part of the index
#combined_df.reset_index(inplace=True)

In [67]:
combined_df

                    HAL                            TIINDIA               \
                  Close    Adj Close   Volume        Close    Adj Close
Date
2021-04-01   517.825012   487.859375  1961258  1198.349976  1190.824951
2021-04-05   499.950012   471.018738   579288  1158.949951  1151.672241
2021-04-06   500.125000   471.183624   322770  1148.150024  1140.940063
2021-04-07   502.950012   473.845062   416420  1170.650024  1163.298828
2021-04-08   505.174988   475.941315   287444  1170.699951  1163.348511
...                 ...          ...      ...          ...          ...
2024-04-24  3946.699951  3946.699951  4429158  3607.399902  3607.399902
2024-04-25  4000.750000  4000.750000  2632613  3573.850098  3573.850098
2024-04-26  3984.399902  3984.399902  1432727  3624.000000  3624.000000
2024-04-29  4017.699951  4017.699951  1202126  3707.600098  3707.600098
2024-04-30  3939.350098  3939.350098  2054258  3742.600098  3742.600098

                         CGPOWER                             TRENT  ...  \
              Volume       Close   Adj Close   Volume        Close  ...
Date                                                                ...
2021-04-01  282259.0   68.750000   68.199562  2339008   750.849976  ...
2021-04-05   64430.0   66.449997   65.917969  4168801   729.450012  ...
2021-04-06  415517.0   69.750000   69.191551  2329236   703.650024  ...
2021-04-07   80899.0   73.199997   72.613930  7556073   722.049988  ...
2021-04-08   74551.0   76.849998   76.234711  5924401   729.750000  ...
...              ...         ...         ...      ...          ...  ...
2024-04-24   90029.0  545.299988  545.299988  2946108  4221.750000  ...
2024-04-25   82363.0  542.250000  542.250000  1195547  4323.149902  ...
2024-04-26  160742.0  557.599976  557.599976  3578376  4304.850098  ...
2024-04-29  341548.0  559.049988  559.049988  2976092  4314.100098  ...
2024-04-30  191950.0  553.950012  553.950012  1654871  4409.899902  ...

                OIL   BAJAJ-AUTO                        SUPREMEIND  \
             Volume        Close    Adj Close  Volume        Close
Date
2021-04-01   579175  3743.050049  3356.182861  861229  2020.800049
2021-04-05   798931  3598.500000  3226.572754  723573  2009.050049
2021-04-06   589040  3615.500000  3241.815674  501882  1980.199951
2021-04-07   778237  3680.199951  3299.828613  346982  1974.599976
2021-04-08   424219  3649.800049  3272.570801  414020  1981.650024
...             ...          ...          ...     ...          ...
2024-04-24  3184163  8697.099609  8626.985352  319824  4250.450195
2024-04-25  3486606  8734.900391  8664.481445  524667  4303.500000
2024-04-26  6320547  8974.299805  8901.951172  521344  4338.450195
2024-04-29  2961861  8760.099609  8689.477539  299443  4955.149902
2024-04-30  4079150  8903.650391  8831.871094  360403  5062.100098

                                        SJVN
              Adj Close   Volume       Close   Adj Close    Volume
Date
2021-04-01  1935.501221    43191   26.100000   23.077703   1596095
2021-04-05  1924.247314    22228   25.799999   22.812441   1247324
2021-04-06  1896.614868    26345   25.650000   22.679811   1075023
2021-04-07  1891.251221   107713   25.000000   22.105078   5421819
2021-04-08  1898.003906    67005   24.700001   21.839819   4130982
...                 ...      ...         ...         ...       ...
2024-04-24  4235.244141   107095  129.699997  129.699997  15583301
2024-04-25  4288.104492    96264  132.949997  132.949997  25448191
2024-04-26  4322.929688   584275  134.600006  134.600006  35340965
2024-04-29  4937.422852  2767650  137.100006  137.100006  29352480
2024-04-30  5043.990723   900529  134.399994  134.399994  22527023

[760 rows x 30 columns]

In [68]:
combined_df.columns.names=['Company','Info']
combined_df

Company             HAL                            TIINDIA               \
Info              Close    Adj Close   Volume        Close    Adj Close
Date
2021-04-01   517.825012   487.859375  1961258  1198.349976  1190.824951
2021-04-05   499.950012   471.018738   579288  1158.949951  1151.672241
2021-04-06   500.125000   471.183624   322770  1148.150024  1140.940063
2021-04-07   502.950012   473.845062   416420  1170.650024  1163.298828
2021-04-08   505.174988   475.941315   287444  1170.699951  1163.348511
...                 ...          ...      ...          ...          ...
2024-04-24  3946.699951  3946.699951  4429158  3607.399902  3607.399902
2024-04-25  4000.750000  4000.750000  2632613  3573.850098  3573.850098
2024-04-26  3984.399902  3984.399902  1432727  3624.000000  3624.000000
2024-04-29  4017.699951  4017.699951  1202126  3707.600098  3707.600098
2024-04-30  3939.350098  3939.350098  2054258  3742.600098  3742.600098

Company                  CGPOWER                             TRENT  ...  \
Info          Volume       Close   Adj Close   Volume        Close  ...
Date                                                                ...
2021-04-01  282259.0   68.750000   68.199562  2339008   750.849976  ...
2021-04-05   64430.0   66.449997   65.917969  4168801   729.450012  ...
2021-04-06  415517.0   69.750000   69.191551  2329236   703.650024  ...
2021-04-07   80899.0   73.199997   72.613930  7556073   722.049988  ...
2021-04-08   74551.0   76.849998   76.234711  5924401   729.750000  ...
...              ...         ...         ...      ...          ...  ...
2024-04-24   90029.0  545.299988  545.299988  2946108  4221.750000  ...
2024-04-25   82363.0  542.250000  542.250000  1195547  4323.149902  ...
2024-04-26  160742.0  557.599976  557.599976  3578376  4304.850098  ...
2024-04-29  341548.0  559.049988  559.049988  2976092  4314.100098  ...
2024-04-30  191950.0  553.950012  553.950012  1654871  4409.899902  ...

Company         OIL   BAJAJ-AUTO                        SUPREMEIND  \
Info         Volume        Close    Adj Close  Volume        Close
Date
2021-04-01   579175  3743.050049  3356.182861  861229  2020.800049
2021-04-05   798931  3598.500000  3226.572754  723573  2009.050049
2021-04-06   589040  3615.500000  3241.815674  501882  1980.199951
2021-04-07   778237  3680.199951  3299.828613  346982  1974.599976
2021-04-08   424219  3649.800049  3272.570801  414020  1981.650024
...             ...          ...          ...     ...          ...
2024-04-24  3184163  8697.099609  8626.985352  319824  4250.450195
2024-04-25  3486606  8734.900391  8664.481445  524667  4303.500000
2024-04-26  6320547  8974.299805  8901.951172  521344  4338.450195
2024-04-29  2961861  8760.099609  8689.477539  299443  4955.149902
2024-04-30  4079150  8903.650391  8831.871094  360403  5062.100098

Company                                 SJVN
Info          Adj Close   Volume       Close   Adj Close    Volume
Date
2021-04-01  1935.501221    43191   26.100000   23.077703   1596095
2021-04-05  1924.247314    22228   25.799999   22.812441   1247324
2021-04-06  1896.614868    26345   25.650000   22.679811   1075023
2021-04-07  1891.251221   107713   25.000000   22.105078   5421819
2021-04-08  1898.003906    67005   24.700001   21.839819   4130982
...                 ...      ...         ...         ...       ...
2024-04-24  4235.244141   107095  129.699997  129.699997  15583301
2024-04-25  4288.104492    96264  132.949997  132.949997  25448191
2024-04-26  4322.929688   584275  134.600006  134.600006  35340965
2024-04-29  4937.422852  2767650  137.100006  137.100006  29352480
2024-04-30  5043.990723   900529  134.399994  134.399994  22527023

[760 rows x 30 columns]

In [69]:
returns = pd.DataFrame()
for stock in symbol_list:
    returns[stock+' Returns'] = combined_df[stock]['Adj Close'].pct_change()

In [70]:
returns.head()
#calculation of daily returns. 
#The daily percent changes is calculated using the 
#.pct_change(method) in a separate dataframe “returns”.

,HAL Returns,TIINDIA Returns,CGPOWER Returns,TRENT Returns,PRESTIGE Returns,NHPC Returns,OIL Returns,BAJAJ-AUTO Returns,SUPREMEIND Returns,SJVN Returns
Date,,,,,,,,,,
2021-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-04-05,-0.034519,-0.032879,-0.033455,-0.028501,-0.030435,-0.002028,-0.013307,-0.038618,-0.005814,-0.011494
2021-04-06,0.000350,-0.009319,0.049661,-0.035369,0.030055,-0.006097,0.002861,0.004724,-0.014360,-0.005814
2021-04-07,0.005648,0.019597,0.049462,0.026149,0.008429,-0.002045,0.010187,0.017895,-0.002828,-0.025341
2021-04-08,0.004424,0.000043,0.049863,0.010664,0.001447,0.000000,-0.014119,-0.008260,0.003570,-0.012000

In [71]:
(returns.mean())*250

HAL Returns           0.738059
TIINDIA Returns       0.452502
CGPOWER Returns       0.759151
TRENT Returns         0.634918
PRESTIGE Returns      0.576878
NHPC Returns          0.554678
OIL Returns           0.654476
BAJAJ-AUTO Returns    0.344654
SUPREMEIND Returns    0.368591
SJVN Returns          0.673903
dtype: float64

In [72]:
returns.cov()*250

,HAL Returns,TIINDIA Returns,CGPOWER Returns,TRENT Returns,PRESTIGE Returns,NHPC Returns,OIL Returns,BAJAJ-AUTO Returns,SUPREMEIND Returns,SJVN Returns
HAL Returns,0.098963,0.014701,0.010705,0.027233,0.032771,0.034580,0.034370,0.014034,0.013283,0.037088
TIINDIA Returns,0.014701,0.152893,0.033366,0.014508,0.012053,0.018117,0.002663,0.009619,0.020457,0.027563
CGPOWER Returns,0.010705,0.033366,0.139141,0.013567,0.015035,0.011245,0.017130,0.012383,0.010617,0.017527
TRENT Returns,0.027233,0.014508,0.013567,0.101689,0.022798,0.017340,0.008749,0.015973,0.022831,0.024619
PRESTIGE Returns,0.032771,0.012053,0.015035,0.022798,0.162173,0.015465,0.015937,0.018352,0.008795,0.020020
NHPC Returns,0.034580,0.018117,0.011245,0.017340,0.015465,0.125902,0.038841,0.010239,0.018732,0.091563
OIL Returns,0.034370,0.002663,0.017130,0.008749,0.015937,0.038841,0.166479,0.012025,0.011531,0.036067
BAJAJ-AUTO Returns,0.014034,0.009619,0.012383,0.015973,0.018352,0.010239,0.012025,0.051817,0.007442,0.014808
SUPREMEIND Returns,0.013283,0.020457,0.010617,0.022831,0.008795,0.018732,0.011531,0.007442,0.107033,0.026014
SJVN Returns,0.037088,0.027563,0.017527,0.024619,0.020020,0.091563,0.036067,0.014808,0.026014,0.188301

#single run
np.random.seed(101)
weights = np.array(np.random.random(21))
print('Random weights')
print(weights)
print('Rebalanced weights')
weights = weights/np.sum(weights)
print('Portfolio return')
port_ret = np.sum(returns.mean()*250*weights)
print(port_ret)
print('Expected volatility')
port_vol = np.sqrt(np.dot(weights.T, np.dot(returns.cov()*250,weights)))
print(port_vol)
print('Sharpe Ratio')
SR = (port_ret - 0.075)/port_vol
print(SR)

In [73]:
sim = 5000
all_weights = np.zeros((sim, len(symbol_list)))
ret_arr = np.zeros(sim)
vol_arr = np.zeros(sim)
sharpe_arr = np.zeros(sim)

for i in range(sim):
    weights = np.array(np.random.random(10))
    weights = weights/np.sum(weights)
    all_weights[i,:] = weights
    ret_arr[i] = np.sum(returns.mean()*250*weights)
    vol_arr[i] = np.sqrt(np.dot(weights.T,np.dot(returns.cov()*250,weights)))
    sharpe_arr[i] = (ret_arr[i] - 0.075)/vol_arr[i]

In [74]:
sharpe_arr.max()

3.059058857793744

In [75]:
sharpe_arr.argmax()

1351

In [76]:
weights = all_weights[1351,:]
len(weights)

10

In [77]:
df = pd.DataFrame({
    'Symbol': symbol_list,
    'Weight': weights
})

# Sort the DataFrame by the weight values
df_sorted = df.sort_values(by='Weight', ascending=False)
print(df_sorted)

       Symbol    Weight
2     CGPOWER  0.225950
3       TRENT  0.200196
0         HAL  0.198356
6         OIL  0.096982
8  SUPREMEIND  0.077691
9        SJVN  0.069660
7  BAJAJ-AUTO  0.040755
5        NHPC  0.038893
4    PRESTIGE  0.038628
1     TIINDIA  0.012888

In [78]:
stocks = df_sorted['Symbol'].tolist()
stocks

['CGPOWER',
 'TRENT',
 'HAL',
 'OIL',
 'SUPREMEIND',
 'SJVN',
 'BAJAJ-AUTO',
 'NHPC',
 'PRESTIGE',
 'TIINDIA']

In [79]:
prices = []
start_date = '2020-04-01'
for symbol in stocks:
        # Fetch historical data from Yahoo Finance
        data = yf.download(symbol+".NS", start="2020-04-01", end='2020-04-02')
        price_april2020 = data.loc[start_date]['Adj Close']
        prices.append(price_april2020)
df_prices = pd.DataFrame({'Symbol': stocks, 'Price_April2020': prices})

# Display the prices
print(df_prices)

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

       Symbol  Price_April2020
0     CGPOWER         5.257566
1       TRENT       462.846893
2         HAL       243.561844
3         OIL        41.931381
4  SUPREMEIND       801.269653
5        SJVN        16.840117
6  BAJAJ-AUTO      1839.106323
7        NHPC        15.995337
8    PRESTIGE       179.633514
9     TIINDIA       257.003326

In [80]:
prices=[]

In [81]:
start_date = '2024-05-02'
for symbol in stocks:
        # Fetch historical data from Yahoo Finance
        data = yf.download(symbol+".NS", start="2024-05-02", end='2024-05-03')
        price_2024 = data.loc[start_date]['Adj Close']
        prices.append(price_2024)
df_prices2 = pd.DataFrame({'Symbol': stocks, 'Price_2024': prices})

# Display the prices
print(df_prices2)

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

       Symbol   Price_2024
0     CGPOWER   549.049988
1       TRENT  4643.514160
2         HAL  3947.199951
3         OIL   420.299988
4  SUPREMEIND  4794.834961
5        SJVN   137.149994
6  BAJAJ-AUTO  9037.202148
7        NHPC    98.000000
8    PRESTIGE  1400.849976
9     TIINDIA  3791.000000

In [82]:
combined_df = pd.merge(df_prices, df_prices2, on='Symbol')

In [83]:
combined_df = pd.merge(df_sorted, combined_df, on='Symbol')

In [84]:
combined_df

       Symbol    Weight  Price_April2020   Price_2024
0     CGPOWER  0.225950         5.257566   549.049988
1       TRENT  0.200196       462.846893  4643.514160
2         HAL  0.198356       243.561844  3947.199951
3         OIL  0.096982        41.931381   420.299988
4  SUPREMEIND  0.077691       801.269653  4794.834961
5        SJVN  0.069660        16.840117   137.149994
6  BAJAJ-AUTO  0.040755      1839.106323  9037.202148
7        NHPC  0.038893        15.995337    98.000000
8    PRESTIGE  0.038628       179.633514  1400.849976
9     TIINDIA  0.012888       257.003326  3791.000000

In [85]:
portfolio_value = 10000000
combined_df['Investment'] = combined_df['Weight'] * portfolio_value
combined_df['Shares'] = (combined_df['Investment'] / combined_df['Price_April2020']).astype(int)

# Calculate the value of each stock on June 2024
combined_df['Value_2024'] = combined_df['Shares'] * combined_df['Price_2024']

# Calculate total investment used and remaining cash
total_investment_used = (combined_df['Shares'] * combined_df['Price_April2020']).sum()
remaining_cash = portfolio_value - total_investment_used

# Calculate total portfolio value in June 2024 and profit/loss
total_value_2024 = combined_df['Value_2024'].sum()
profit_loss = total_value_2024 - total_investment_used

In [86]:
combined_df

,Symbol,Weight,Price_April2020,Price_2024,Investment,Shares,Value_2024
0,CGPOWER,0.225950,5.257566,549.049988,2.259499e+06,429761,2.359603e+08
1,TRENT,0.200196,462.846893,4643.514160,2.001962e+06,4325,2.008320e+07
2,HAL,0.198356,243.561844,3947.199951,1.983557e+06,8143,3.214205e+07
3,OIL,0.096982,41.931381,420.299988,9.698213e+05,23128,9.720698e+06
4,SUPREMEIND,0.077691,801.269653,4794.834961,7.769087e+05,969,4.646195e+06
5,SJVN,0.069660,16.840117,137.149994,6.966033e+05,41365,5.673209e+06
6,BAJAJ-AUTO,0.040755,1839.106323,9037.202148,4.075540e+05,221,1.997222e+06
7,NHPC,0.038893,15.995337,98.000000,3.889348e+05,24315,2.382870e+06
8,PRESTIGE,0.038628,179.633514,1400.849976,3.862790e+05,2150,3.011827e+06
9,TIINDIA,0.012888,257.003326,3791.000000,1.288808e+05,501,1.899291e+06

In [87]:
# Display the final DataFrame and summary
print(combined_df)
print("\nSummary:")
print(f"Total Investment Used: Rs.{total_investment_used:.2f}")
print(f"Remaining Cash: Rs.{remaining_cash:.2f}")
print(f"Total Portfolio Value in June 2024: Rs.{total_value_2024:.2f}")
print(f"Total Profit: Rs.{profit_loss:.2f}")
print(f"Total Profit %: {profit_loss/total_investment_used*100:.2f}")

       Symbol    Weight  Price_April2020   Price_2024    Investment  Shares  \
0     CGPOWER  0.225950         5.257566   549.049988  2.259499e+06  429761
1       TRENT  0.200196       462.846893  4643.514160  2.001962e+06    4325
2         HAL  0.198356       243.561844  3947.199951  1.983557e+06    8143
3         OIL  0.096982        41.931381   420.299988  9.698213e+05   23128
4  SUPREMEIND  0.077691       801.269653  4794.834961  7.769087e+05     969
5        SJVN  0.069660        16.840117   137.149994  6.966033e+05   41365
6  BAJAJ-AUTO  0.040755      1839.106323  9037.202148  4.075540e+05     221
7        NHPC  0.038893        15.995337    98.000000  3.889348e+05   24315
8    PRESTIGE  0.038628       179.633514  1400.849976  3.862790e+05    2150
9     TIINDIA  0.012888       257.003326  3791.000000  1.288808e+05     501

     Value_2024
0  2.359603e+08
1  2.008320e+07
2  3.214205e+07
3  9.720698e+06
4  4.646195e+06
5  5.673209e+06
6  1.997222e+06
7  2.382870e+06
8  3.011827e+06
9  1.899291e+06

Summary:
Total Investment Used: Rs.9997784.47
Remaining Cash: Rs.2215.53
Total Portfolio Value in June 2024: Rs.317516832.56
Total Profit: Rs.307519048.09
Total Profit %: 3075.87

In [88]:
prices = []

In [89]:
start_date = '2024-05-02'
for symbol in stocks:
        # Fetch historical data from Yahoo Finance
        data = yf.download(symbol+".NS", start="2024-05-02", end='2024-05-03')
        price_april2020 = data.loc[start_date]['Adj Close']
        prices.append(price_april2020)
df_prices2 = pd.DataFrame({'Symbol': stocks, 'Price_May2024': prices})

# Display the prices
print(df_prices2)

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

       Symbol  Price_May2024
0     CGPOWER     549.049988
1       TRENT    4643.514160
2         HAL    3947.199951
3         OIL     420.299988
4  SUPREMEIND    4794.834961
5        SJVN     137.149994
6  BAJAJ-AUTO    9037.202148
7        NHPC      98.000000
8    PRESTIGE    1400.849976
9     TIINDIA    3791.000000

In [90]:
prices = []
start_date = '2024-06-03'
for symbol in stocks:
        # Fetch historical data from Yahoo Finance
        data = yf.download(symbol+".NS", start="2024-06-03", end='2024-06-04')
        price_2024 = data.loc[start_date]['Adj Close']
        prices.append(price_2024)
df_prices3 = pd.DataFrame({'Symbol': stocks, 'Price_2024': prices})

# Display the prices
print(df_prices3)

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

       Symbol   Price_2024
0     CGPOWER   686.250000
1       TRENT  4662.200195
2         HAL  5273.649902
3         OIL   446.233337
4  SUPREMEIND  5547.382812
5        SJVN   143.149994
6  BAJAJ-AUTO  9260.190430
7        NHPC   113.150002
8    PRESTIGE  1735.199951
9     TIINDIA  3835.300049

In [91]:
combined_df = pd.merge(df_prices2, df_prices3, on='Symbol')

In [92]:
combined_df = pd.merge(df_sorted, combined_df, on='Symbol')

In [93]:
combined_df

       Symbol    Weight  Price_May2024   Price_2024
0     CGPOWER  0.225950     549.049988   686.250000
1       TRENT  0.200196    4643.514160  4662.200195
2         HAL  0.198356    3947.199951  5273.649902
3         OIL  0.096982     420.299988   446.233337
4  SUPREMEIND  0.077691    4794.834961  5547.382812
5        SJVN  0.069660     137.149994   143.149994
6  BAJAJ-AUTO  0.040755    9037.202148  9260.190430
7        NHPC  0.038893      98.000000   113.150002
8    PRESTIGE  0.038628    1400.849976  1735.199951
9     TIINDIA  0.012888    3791.000000  3835.300049

In [94]:
portfolio_value = 10000000
combined_df['Investment'] = combined_df['Weight'] * portfolio_value
combined_df['Shares'] = (combined_df['Investment'] / combined_df['Price_May2024']).astype(int)

# Calculate the value of each stock on 1st June 2024
combined_df['Value_2024'] = combined_df['Shares'] * combined_df['Price_2024']

# Calculate total investment used and remaining cash
total_investment_used = (combined_df['Shares'] * combined_df['Price_May2024']).sum()
remaining_cash = portfolio_value - total_investment_used

# Calculate total portfolio value in June 2024 and profit/loss
total_value_2024 = combined_df['Value_2024'].sum()
profit_loss = total_value_2024 - total_investment_used

In [95]:
combined_df

,Symbol,Weight,Price_May2024,Price_2024,Investment,Shares,Value_2024
0,CGPOWER,0.225950,549.049988,686.250000,2.259499e+06,4115,2.823919e+06
1,TRENT,0.200196,4643.514160,4662.200195,2.001962e+06,431,2.009408e+06
2,HAL,0.198356,3947.199951,5273.649902,1.983557e+06,502,2.647372e+06
3,OIL,0.096982,420.299988,446.233337,9.698213e+05,2307,1.029460e+06
4,SUPREMEIND,0.077691,4794.834961,5547.382812,7.769087e+05,162,8.986760e+05
5,SJVN,0.069660,137.149994,143.149994,6.966033e+05,5079,7.270588e+05
6,BAJAJ-AUTO,0.040755,9037.202148,9260.190430,4.075540e+05,45,4.167086e+05
7,NHPC,0.038893,98.000000,113.150002,3.889348e+05,3968,4.489792e+05
8,PRESTIGE,0.038628,1400.849976,1735.199951,3.862790e+05,275,4.771800e+05
9,TIINDIA,0.012888,3791.000000,3835.300049,1.288808e+05,33,1.265649e+05

In [96]:
# Display the final DataFrame and summary
print(combined_df)
print("\nSummary:")
print(f"Total Investment Used: Rs.{total_investment_used:.2f}")
print(f"Remaining Cash: Rs.{remaining_cash:.2f}")
print(f"Total Portfolio Value in June 2024: Rs.{total_value_2024:.2f}")
print(f"Total Profit: Rs.{profit_loss:.2f}")
print(f"Total Profit %: {profit_loss/total_investment_used*100:.2f}")

       Symbol    Weight  Price_May2024   Price_2024    Investment  Shares  \
0     CGPOWER  0.225950     549.049988   686.250000  2.259499e+06    4115
1       TRENT  0.200196    4643.514160  4662.200195  2.001962e+06     431
2         HAL  0.198356    3947.199951  5273.649902  1.983557e+06     502
3         OIL  0.096982     420.299988   446.233337  9.698213e+05    2307
4  SUPREMEIND  0.077691    4794.834961  5547.382812  7.769087e+05     162
5        SJVN  0.069660     137.149994   143.149994  6.966033e+05    5079
6  BAJAJ-AUTO  0.040755    9037.202148  9260.190430  4.075540e+05      45
7        NHPC  0.038893      98.000000   113.150002  3.889348e+05    3968
8    PRESTIGE  0.038628    1400.849976  1735.199951  3.862790e+05     275
9     TIINDIA  0.012888    3791.000000  3835.300049  1.288808e+05      33

     Value_2024
0  2.823919e+06
1  2.009408e+06
2  2.647372e+06
3  1.029460e+06
4  8.986760e+05
5  7.270588e+05
6  4.167086e+05
7  4.489792e+05
8  4.771800e+05
9  1.265649e+05

Summary:
Total Investment Used: Rs.9991044.67
Remaining Cash: Rs.8955.33
Total Portfolio Value in June 2024: Rs.11605327.09
Total Profit: Rs.1614282.42
Total Profit %: 16.16